// Static Python 3.12 symbol tables powering browser-side autocomplete in the Snapjaw code editor.
export interface PythonModuleMembers {
  functions?: string[];
  classes?: string[];
  values?: string[];
}

export const PYTHON_KEYWORDS: string[] = [
  "False",
  "None",
  "True",
  "and",
  "as",
  "assert",
  "async",
  "await",
  "break",
  "case",
  "class",
  "continue",
  "def",
  "del",
  "elif",
  "else",
  "except",
  "finally",
  "for",
  "from",
  "global",
  "if",
  "import",
  "in",
  "is",
  "lambda",
  "match",
  "nonlocal",
  "not",
  "or",
  "pass",
  "raise",
  "return",
  "try",
  "type",
  "while",
  "with",
  "yield",
];

export const PYTHON_BUILTIN_FUNCTIONS: string[] = [
  "abs(x)",
  "aiter(async_iterable)",
  "all(iterable)",
  "anext(async_iterator, default)",
  "any(iterable)",
  "ascii(object)",
  "bin(number)",
  "bool(object)",
  "breakpoint(*args, **kws)",
  "bytearray(source, encoding, errors)",
  "bytes(source, encoding, errors)",
  "callable(object)",
  "chr(i)",
  "classmethod(function)",
  "compile(source, filename, mode, flags, dont_inherit, optimize)",
  "complex(real, imag)",
  "delattr(object, name)",
  "dict(**kwargs)",
  "dir(object)",
  "divmod(a, b)",
  "enumerate(iterable, start)",
  "eval(source, globals, locals)",
  "exec(source, globals, locals)",
  "filter(function, iterable)",
  "float(x)",
  "format(value, format_spec)",
  "frozenset(iterable)",
  "getattr(object, name, default)",
  "globals()",
  "hasattr(object, name)",
  "hash(object)",
  "help(request)",
  "hex(number)",
  "id(object)",
  "input(prompt)",
  "int(x, base)",
  "isinstance(object, classinfo)",
  "issubclass(class, classinfo)",
  "iter(object, sentinel)",
  "len(object)",
  "list(iterable)",
  "locals()",
  "map(function, iterable)",
  "max(iterable, key, default)",
  "memoryview(object)",
  "min(iterable, key, default)",
  "next(iterator, default)",
  "object()",
  "oct(number)",
  "open(file, mode)",
  "ord(c)",
  "pow(base, exp, mod)",
  "print(*values, sep, end)",
  "property(fget, fset, fdel, doc)",
  "range(start, stop, step)",
  "repr(object)",
  "reversed(sequence)",
  "round(number, ndigits)",
  "set(iterable)",
  "setattr(object, name, value)",
  "slice(start, stop, step)",
  "sorted(iterable, key, reverse)",
  "staticmethod(function)",
  "str(object, encoding, errors)",
  "sum(iterable, start)",
  "super(type, object_or_type)",
  "tuple(iterable)",
  "type(object, bases, dict)",
  "vars(object)",
  "zip(*iterables)",
];

export const PYTHON_BUILTIN_CLASSES: string[] = [
  "int",
  "float",
  "str",
  "list",
  "dict",
  "set",
  "tuple",
  "bool",
  "bytes",
  "bytearray",
  "frozenset",
  "complex",
  "object",
  "type",
  "super",
  "memoryview",
  "slice",
  "range",
  "enumerate",
  "zip",
  "map",
  "filter",
  "reversed",
  "property",
  "classmethod",
  "staticmethod",
  "Exception",
];

export const PYTHON_BUILTIN_VALUES: string[] = [
  "__name__",
  "__file__",
  "__doc__",
  "NotImplemented",
  "Ellipsis",
];

export const PYTHON_EXCEPTIONS: string[] = [
  "ArithmeticError",
  "AssertionError",
  "AttributeError",
  "BaseException",
  "BaseExceptionGroup",
  "BlockingIOError",
  "BrokenPipeError",
  "BufferError",
  "BytesWarning",
  "ChildProcessError",
  "ConnectionAbortedError",
  "ConnectionError",
  "ConnectionRefusedError",
  "ConnectionResetError",
  "DeprecationWarning",
  "EOFError",
  "EncodingWarning",
  "Exception",
  "ExceptionGroup",
  "FileExistsError",
  "FileNotFoundError",
  "FloatingPointError",
  "FutureWarning",
  "GeneratorExit",
  "ImportError",
  "ImportWarning",
  "IndentationError",
  "IndexError",
  "InterruptedError",
  "IsADirectoryError",
  "KeyError",
  "KeyboardInterrupt",
  "LookupError",
  "MemoryError",
  "ModuleNotFoundError",
  "NameError",
  "NotADirectoryError",
  "NotImplementedError",
  "OSError",
  "OverflowError",
  "PendingDeprecationWarning",
  "PermissionError",
  "ProcessLookupError",
  "RecursionError",
  "ReferenceError",
  "ResourceWarning",
  "RuntimeError",
  "RuntimeWarning",
  "StopAsyncIteration",
  "StopIteration",
  "SyntaxError",
  "SyntaxWarning",
  "SystemError",
  "SystemExit",
  "TabError",
  "TimeoutError",
  "TypeError",
  "UnboundLocalError",
  "UnicodeDecodeError",
  "UnicodeEncodeError",
  "UnicodeError",
  "UnicodeTranslateError",
  "UnicodeWarning",
  "UserWarning",
  "ValueError",
  "Warning",
  "ZeroDivisionError",
];

export const PYTHON_MODULE_NAMES: string[] = [
  "abc",
  "argparse",
  "array",
  "ast",
  "asyncio",
  "base64",
  "binascii",
  "bisect",
  "builtins",
  "bz2",
  "calendar",
  "cmath",
  "code",
  "codecs",
  "codeop",
  "collections",
  "colorsys",
  "compileall",
  "concurrent",
  "configparser",
  "contextlib",
  "contextvars",
  "copy",
  "csv",
  "ctypes",
  "curses",
  "dataclasses",
  "datetime",
  "dbm",
  "decimal",
  "difflib",
  "dis",
  "doctest",
  "email",
  "encodings",
  "enum",
  "errno",
  "faulthandler",
  "fcntl",
  "filecmp",
  "fnmatch",
  "fractions",
  "ftplib",
  "functools",
  "gc",
  "getopt",
  "getpass",
  "gettext",
  "glob",
  "graphlib",
  "grp",
  "gzip",
  "hashlib",
  "heapq",
  "hmac",
  "html",
  "http",
  "imaplib",
  "importlib",
  "inspect",
  "io",
  "ipaddress",
  "itertools",
  "json",
  "keyword",
  "linecache",
  "locale",
  "logging",
  "lzma",
  "mailbox",
  "marshal",
  "math",
  "mimetypes",
  "modulefinder",
  "multiprocessing",
  "netrc",
  "ntpath",
  "numbers",
  "operator",
  "optparse",
  "os",
  "pathlib",
  "pdb",
  "pickle",
  "pkgutil",
  "platform",
  "plistlib",
  "poplib",
  "posixpath",
  "pprint",
  "profile",
  "pty",
  "pwd",
  "py_compile",
  "pydoc",
  "queue",
  "random",
  "re",
  "readline",
  "reprlib",
  "runpy",
  "sched",
  "secrets",
  "select",
  "shelve",
  "shlex",
  "shutil",
  "signal",
  "site",
  "smtplib",
  "socket",
  "sqlite3",
  "ssl",
  "stat",
  "statistics",
  "string",
  "stringprep",
  "struct",
  "subprocess",
  "symtable",
  "sys",
  "sysconfig",
  "syslog",
  "tabnanny",
  "tarfile",
  "tempfile",
  "textwrap",
  "this",
  "threading",
  "time",
  "timeit",
  "tkinter",
  "token",
  "tokenize",
  "tomllib",
  "traceback",
  "tracemalloc",
  "tty",
  "turtle",
  "types",
  "typing",
  "unicodedata",
  "unittest",
  "urllib",
  "uuid",
  "venv",
  "warnings",
  "wave",
  "weakref",
  "webbrowser",
  "wsgiref",
  "xml",
  "xmlrpc",
  "zipapp",
  "zipfile",
  "zipimport",
  "zlib",
  "zoneinfo",
];

export const PYTHON_MODULE_MEMBERS: Record<string, PythonModuleMembers> = {
  base64: {
    functions: [
      "b64encode(s, altchars)",
      "b64decode(s, altchars, validate)",
      "standard_b64encode(s)",
      "standard_b64decode(s)",
      "urlsafe_b64encode(s)",
      "urlsafe_b64decode(s)",
      "b32encode(s)",
      "b32decode(s, casefold, map01)",
      "b32hexencode(s)",
      "b32hexdecode(s, casefold)",
      "b16encode(s)",
      "b16decode(s, casefold)",
      "b85encode(b, pad)",
      "b85decode(b)",
      "a85encode(b, foldspaces, wrapcol, pad, adobe)",
      "a85decode(b, foldspaces, adobe, ignorechars)",
      "encode(input, output)",
      "decode(input, output)",
      "encodebytes(s)",
      "decodebytes(s)",
    ],
    values: [
      "MAXBINSIZE",
      "MAXLINESIZE",
      "b64alphabet",
      "b32alphabet",
      "b16alphabet",
      "a85alphabet",
      "b85alphabet",
    ],
  },
  bisect: {
    functions: [
      "bisect_left(a, x, lo, hi, key)",
      "bisect_right(a, x, lo, hi, key)",
      "bisect(a, x, lo, hi, key)",
      "insort_left(a, x, lo, hi, key)",
      "insort_right(a, x, lo, hi, key)",
      "insort(a, x, lo, hi, key)",
    ],
  },
  calendar: {
    functions: [
      "monthcalendar(year, month)",
      "monthrange(year, month)",
      "weekday(year, month, day)",
      "isleap(year)",
      "leapdays(y1, y2)",
      "month(theyear, themonth, w, l)",
      "prmonth(theyear, themonth, w, l)",
      "calendar(year, w, l, c, m)",
      "prcal(year, w, l, c, m)",
      "timegm(tuple)",
      "weekheader(width)",
      "setfirstweekday(firstweekday)",
      "firstweekday()",
    ],
    classes: [
      "Calendar",
      "TextCalendar",
      "HTMLCalendar",
      "LocaleTextCalendar",
      "LocaleHTMLCalendar",
      "IllegalMonthError",
      "IllegalWeekdayError",
      "Day",
      "Month",
    ],
    values: [
      "day_name",
      "day_abbr",
      "month_name",
      "month_abbr",
      "MONDAY",
      "TUESDAY",
      "WEDNESDAY",
      "THURSDAY",
      "FRIDAY",
      "SATURDAY",
      "SUNDAY",
      "EPOCH",
    ],
  },
  collections: {
    functions: ["namedtuple(typename, fieldnames, rename, defaults, module)"],
    classes: [
      "deque",
      "defaultdict",
      "Counter",
      "OrderedDict",
      "ChainMap",
      "UserDict",
      "UserList",
      "UserString",
    ],
  },
  colorsys: {
    functions: [
      "rgb_to_hsv(r, g, b)",
      "hsv_to_rgb(h, s, v)",
      "rgb_to_hls(r, g, b)",
      "hls_to_rgb(h, l, s)",
      "rgb_to_yiq(r, g, b)",
      "yiq_to_rgb(y, i, q)",
    ],
  },
  contextlib: {
    functions: [
      "contextmanager(func)",
      "asynccontextmanager(func)",
      "closing(thing)",
      "suppress(*exceptions)",
      "redirect_stdout(new_target)",
      "redirect_stderr(new_target)",
      "nullcontext(enter_result)",
      "chdir(path)",
      "aclosing(thing)",
    ],
    classes: [
      "ExitStack",
      "AsyncExitStack",
      "ContextDecorator",
      "AsyncContextDecorator",
      "AbstractContextManager",
      "AbstractAsyncContextManager",
    ],
  },
  copy: {
    functions: ["copy(x)", "deepcopy(x, memo)"],
    classes: ["Error"],
  },
  csv: {
    functions: [
      "reader(csvfile, dialect, fmtparams)",
      "writer(csvfile, dialect, fmtparams)",
      "register_dialect(name, dialect, fmtparams)",
      "unregister_dialect(name)",
      "get_dialect(name)",
      "list_dialects()",
      "field_size_limit(new_limit)",
    ],
    classes: [
      "DictReader",
      "DictWriter",
      "Sniffer",
      "Dialect",
      "excel",
      "excel_tab",
      "unix_dialect",
      "Error",
    ],
    values: [
      "QUOTE_MINIMAL",
      "QUOTE_ALL",
      "QUOTE_NONNUMERIC",
      "QUOTE_NONE",
      "QUOTE_STRINGS",
      "QUOTE_NOTNULL",
    ],
  },
  dataclasses: {
    functions: [
      "dataclass(cls, init, repr, eq, order, unsafe_hash, frozen, match_args, kw_only, slots, weakref_slot)",
      "field(default, default_factory, init, repr, hash, compare, metadata, kw_only)",
      "fields(class_or_instance)",
      "asdict(obj, dict_factory)",
      "astuple(obj, tuple_factory)",
      "make_dataclass(cls_name, fields, bases, namespace, init, repr, eq, order, unsafe_hash, frozen, match_args, kw_only, slots, weakref_slot)",
      "replace(obj, **changes)",
      "is_dataclass(obj)",
    ],
    classes: ["Field", "InitVar", "FrozenInstanceError"],
    values: ["KW_ONLY", "MISSING"],
  },
  datetime: {
    classes: ["datetime", "date", "time", "timedelta", "timezone", "tzinfo"],
    values: ["MINYEAR", "MAXYEAR", "UTC"],
  },
  "datetime.datetime": {
    functions: [
      "now(tz)",
      "today()",
      "fromtimestamp(timestamp, tz)",
      "fromisoformat(date_string)",
      "fromisocalendar(year, week, day)",
      "fromordinal(ordinal)",
      "strptime(date_string, format)",
      "combine(date, time, tzinfo)",
      "timestamp()",
      "date()",
      "time()",
      "timetz()",
      "astimezone(tz)",
      "weekday()",
      "isoweekday()",
      "isocalendar()",
      "isoformat(sep, timespec)",
      "ctime()",
      "strftime(format)",
      "replace(year, month, day, hour, minute, second, microsecond, tzinfo, fold)",
      "toordinal()",
      "tzname()",
      "utcoffset()",
      "dst()",
    ],
    values: ["min", "max", "resolution"],
  },
  decimal: {
    functions: ["getcontext()", "setcontext(context)", "localcontext(ctx)"],
    classes: [
      "Decimal",
      "Context",
      "DecimalException",
      "InvalidOperation",
      "DivisionByZero",
      "Overflow",
      "Underflow",
      "Inexact",
      "Rounded",
      "Subnormal",
      "Clamped",
      "ConversionSyntax",
      "FloatOperation",
    ],
    values: [
      "ROUND_HALF_EVEN",
      "ROUND_HALF_UP",
      "ROUND_DOWN",
      "ROUND_UP",
      "ROUND_CEILING",
      "ROUND_FLOOR",
      "ROUND_HALF_DOWN",
      "ROUND_05UP",
      "MAX_PREC",
      "MAX_EMAX",
      "MIN_EMIN",
      "MIN_ETINY",
      "DefaultContext",
      "BasicContext",
      "ExtendedContext",
    ],
  },
  enum: {
    functions: [
      "unique(enumeration)",
      "verify(enumeration)",
      "member(obj)",
      "nonmember(obj)",
      "global_enum(enumeration)",
      "show_flag_values(value)",
    ],
    classes: ["Enum", "IntEnum", "StrEnum", "IntFlag", "Flag", "ReprEnum", "EnumType", "auto"],
  },
  fractions: {
    classes: ["Fraction"],
  },
  functools: {
    functions: [
      "reduce(function, iterable, initializer)",
      "partial(func, *args, **keywords)",
      "lru_cache(maxsize, typed)",
      "cache(user_function)",
      "wraps(wrapped, assigned, updated)",
      "cached_property(func)",
      "total_ordering(cls)",
      "cmp_to_key(mycmp)",
      "singledispatch(func)",
      "singledispatchmethod(func)",
      "partialmethod(func, *args, **keywords)",
      "update_wrapper(wrapper, wrapped, assigned, updated)",
    ],
    values: ["WRAPPER_ASSIGNMENTS", "WRAPPER_UPDATES"],
  },
  glob: {
    functions: [
      "glob(pathname, root_dir, dir_fd, recursive)",
      "iglob(pathname, root_dir, dir_fd, recursive)",
      "escape(pathname)",
      "has_magic(s)",
    ],
  },
  hashlib: {
    functions: [
      "sha256(data)",
      "sha1(data)",
      "md5(data)",
      "sha512(data)",
      "sha384(data)",
      "sha224(data)",
      "sha3_256(data)",
      "sha3_512(data)",
      "sha3_384(data)",
      "sha3_224(data)",
      "blake2b(data, digest_size, key, salt, person)",
      "blake2s(data, digest_size, key, salt, person)",
      "shake_128(data)",
      "shake_256(data)",
      "new(name, data)",
      "file_digest(fileobj, digest)",
      "pbkdf2_hmac(hash_name, password, salt, iterations, dklen)",
      "scrypt(password, salt, n, r, p, maxmem, dklen)",
    ],
    values: ["algorithms_guaranteed", "algorithms_available"],
  },
  heapq: {
    functions: [
      "heappush(heap, item)",
      "heappop(heap)",
      "heapify(heap)",
      "heapreplace(heap, item)",
      "heappushpop(heap, item)",
      "nlargest(n, iterable, key)",
      "nsmallest(n, iterable, key)",
      "merge(*iterables, key, reverse)",
    ],
  },
  io: {
    functions: ["open(file, mode, buffering, encoding, errors, newline, closefd, opener)"],
    classes: [
      "StringIO",
      "BytesIO",
      "TextIOWrapper",
      "BufferedReader",
      "BufferedWriter",
      "BufferedRandom",
      "BufferedRWPair",
      "FileIO",
      "IncrementalNewlineDecoder",
      "UnsupportedOperation",
    ],
    values: ["SEEK_SET", "SEEK_CUR", "SEEK_END"],
  },
  itertools: {
    functions: [
      "count(start, step)",
      "cycle(iterable)",
      "repeat(object, times)",
      "chain(*iterables)",
      "islice(iterable, stop)",
      "product(*iterables, repeat)",
      "permutations(iterable, r)",
      "combinations(iterable, r)",
      "combinations_with_replacement(iterable, r)",
      "groupby(iterable, key)",
      "accumulate(iterable, func, initial)",
      "zip_longest(*iterables, fillvalue)",
      "takewhile(predicate, iterable)",
      "dropwhile(predicate, iterable)",
      "filterfalse(predicate, iterable)",
      "starmap(function, iterable)",
      "tee(iterable, n)",
      "compress(data, selectors)",
      "pairwise(iterable)",
      "batched(iterable, n)",
    ],
  },
  json: {
    functions: [
      "dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys)",
      "loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook)",
      "dump(obj, fp, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys)",
      "load(fp, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook)",
    ],
    classes: ["JSONDecoder", "JSONEncoder", "JSONDecodeError"],
  },
  logging: {
    functions: [
      "getLogger(name)",
      "basicConfig(**kwargs)",
      "debug(msg, *args, **kwargs)",
      "info(msg, *args, **kwargs)",
      "warning(msg, *args, **kwargs)",
      "error(msg, *args, **kwargs)",
      "critical(msg, *args, **kwargs)",
      "exception(msg, *args, **kwargs)",
      "log(level, msg, *args, **kwargs)",
      "disable(level)",
      "shutdown()",
      "addLevelName(level, levelName)",
      "getLevelName(level)",
      "captureWarnings(capture)",
      "makeLogRecord(dict)",
    ],
    classes: [
      "Logger",
      "Handler",
      "StreamHandler",
      "FileHandler",
      "NullHandler",
      "Formatter",
      "LogRecord",
      "Filter",
      "LoggerAdapter",
      "PlaceHolder",
    ],
    values: ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL", "NOTSET", "BASIC_FORMAT"],
  },
  math: {
    functions: [
      "sqrt(x)",
      "ceil(x)",
      "floor(x)",
      "fabs(x)",
      "pow(x, y)",
      "exp(x)",
      "log(x, base)",
      "log2(x)",
      "log10(x)",
      "sin(x)",
      "cos(x)",
      "tan(x)",
      "asin(x)",
      "acos(x)",
      "atan(x)",
      "atan2(y, x)",
      "degrees(x)",
      "radians(x)",
      "hypot(*coordinates)",
      "dist(p, q)",
      "factorial(n)",
      "gcd(*integers)",
      "isqrt(n)",
      "fsum(iterable)",
      "prod(iterable, start)",
      "trunc(x)",
      "fmod(x, y)",
      "isclose(a, b, rel_tol, abs_tol)",
      "isfinite(x)",
      "isnan(x)",
    ],
    values: ["pi", "e", "tau", "inf", "nan"],
  },
  os: {
    functions: [
      "getcwd()",
      "listdir(path)",
      "mkdir(path, mode)",
      "makedirs(name, mode, exist_ok)",
      "remove(path)",
      "rmdir(path)",
      "unlink(path)",
      "rename(src, dst)",
      "replace(src, dst)",
      "stat(path)",
      "chdir(path)",
      "getenv(key, default)",
      "putenv(name, value)",
      "system(command)",
      "popen(cmd, mode, buffering)",
      "walk(top, topdown, onerror, followlinks)",
      "scandir(path)",
      "fspath(path)",
      "access(path, mode)",
      "chmod(path, mode)",
      "symlink(src, dst)",
      "readlink(path)",
      "urandom(size)",
      "cpu_count()",
      "getpid()",
      "get_terminal_size(fd)",
    ],
    classes: ["PathLike", "DirEntry"],
    values: [
      "environ",
      "sep",
      "altsep",
      "pathsep",
      "linesep",
      "name",
      "curdir",
      "pardir",
      "extsep",
      "devnull",
    ],
  },
  "os.path": {
    functions: [
      "join(path, *paths)",
      "exists(path)",
      "isfile(path)",
      "isdir(path)",
      "getsize(filename)",
      "basename(path)",
      "dirname(path)",
      "splitext(path)",
      "split(path)",
      "abspath(path)",
      "realpath(filename, strict)",
      "relpath(path, start)",
      "normpath(path)",
      "normcase(path)",
      "isabs(path)",
      "islink(path)",
      "ismount(path)",
      "expanduser(path)",
      "expandvars(path)",
      "getmtime(filename)",
      "getctime(filename)",
      "getatime(filename)",
      "samefile(f1, f2)",
      "commonpath(paths)",
      "commonprefix(list)",
      "splitdrive(path)",
    ],
    values: ["sep", "altsep", "pathsep", "curdir", "pardir", "extsep", "devnull"],
  },
  pathlib: {
    classes: ["Path", "PurePath", "PosixPath", "WindowsPath", "PurePosixPath", "PureWindowsPath"],
  },
  pprint: {
    functions: [
      "pprint(object, stream, indent, width, depth, compact, sort_dicts, underscore_numbers)",
      "pformat(object, indent, width, depth, compact, sort_dicts, underscore_numbers)",
      "pp(object, stream, indent, width, depth, compact, sort_dicts, underscore_numbers)",
      "isreadable(object)",
      "isrecursive(object)",
      "saferepr(object)",
    ],
    classes: ["PrettyPrinter"],
  },
  queue: {
    classes: ["Queue", "LifoQueue", "PriorityQueue", "SimpleQueue", "Empty", "Full"],
  },
  random: {
    functions: [
      "random()",
      "randint(a, b)",
      "choice(seq)",
      "randrange(start, stop, step)",
      "shuffle(x)",
      "sample(population, k, counts)",
      "uniform(a, b)",
      "choices(population, weights, cum_weights, k)",
      "seed(a, version)",
      "getrandbits(k)",
      "gauss(mu, sigma)",
      "normalvariate(mu, sigma)",
      "triangular(low, high, mode)",
      "expovariate(lambd)",
      "betavariate(alpha, beta)",
      "randbytes(n)",
      "getstate()",
      "setstate(state)",
    ],
    classes: ["Random", "SystemRandom"],
  },
  re: {
    functions: [
      "compile(pattern, flags)",
      "search(pattern, string, flags)",
      "match(pattern, string, flags)",
      "fullmatch(pattern, string, flags)",
      "findall(pattern, string, flags)",
      "finditer(pattern, string, flags)",
      "sub(pattern, repl, string, count, flags)",
      "subn(pattern, repl, string, count, flags)",
      "split(pattern, string, maxsplit, flags)",
      "escape(pattern)",
      "purge()",
    ],
    classes: ["Pattern", "Match"],
    values: [
      "IGNORECASE",
      "MULTILINE",
      "DOTALL",
      "VERBOSE",
      "ASCII",
      "UNICODE",
      "LOCALE",
      "NOFLAG",
    ],
  },
  secrets: {
    functions: [
      "token_hex(nbytes)",
      "token_urlsafe(nbytes)",
      "token_bytes(nbytes)",
      "choice(seq)",
      "randbelow(exclusive_upper_bound)",
      "randbits(k)",
      "compare_digest(a, b)",
    ],
  },
  shutil: {
    functions: [
      "copy(src, dst)",
      "copy2(src, dst)",
      "copyfile(src, dst)",
      "copytree(src, dst, symlinks, ignore, copy_function, ignore_dangling_symlinks, dirs_exist_ok)",
      "move(src, dst)",
      "rmtree(path, ignore_errors, onerror)",
      "copyfileobj(fsrc, fdst, length)",
      "disk_usage(path)",
      "which(cmd, mode, path)",
      "make_archive(base_name, format, root_dir, base_dir)",
      "unpack_archive(filename, extract_dir, format)",
      "get_archive_formats()",
      "get_unpack_formats()",
      "copymode(src, dst)",
      "copystat(src, dst)",
      "chown(path, user, group)",
    ],
  },
  statistics: {
    functions: [
      "mean(data)",
      "median(data)",
      "mode(data)",
      "stdev(data, xbar)",
      "variance(data, xbar)",
      "pstdev(data, mu)",
      "pvariance(data, mu)",
      "median_low(data)",
      "median_high(data)",
      "median_grouped(data, interval)",
      "multimode(data)",
      "harmonic_mean(data, weights)",
      "geometric_mean(data)",
      "fmean(data, weights)",
      "quantiles(data, n)",
      "covariance(x, y)",
      "correlation(x, y)",
      "linear_regression(x, y, proportional)",
    ],
    classes: ["StatisticsError", "NormalDist"],
  },
  string: {
    functions: ["capwords(s, sep)"],
    classes: ["Template", "Formatter"],
    values: [
      "ascii_lowercase",
      "ascii_uppercase",
      "ascii_letters",
      "digits",
      "hexdigits",
      "octdigits",
      "punctuation",
      "printable",
      "whitespace",
    ],
  },
  subprocess: {
    functions: [
      "run(args, capture_output, shell, check, timeout, input, text, encoding, errors, cwd, env, stdout, stderr)",
      "call(args, timeout, shell)",
      "check_call(args, timeout, shell)",
      "check_output(args, timeout, shell, input, text, encoding, errors, cwd, env, stderr)",
      "getoutput(cmd)",
      "getstatusoutput(cmd)",
    ],
    classes: [
      "Popen",
      "CompletedProcess",
      "CalledProcessError",
      "TimeoutExpired",
      "SubprocessError",
    ],
    values: ["PIPE", "STDOUT", "DEVNULL"],
  },
  sys: {
    functions: [
      "exit(status)",
      "getsizeof(object, default)",
      "exc_info()",
      "getrecursionlimit()",
      "setrecursionlimit(limit)",
      "settrace(function)",
      "gettrace()",
      "setprofile(function)",
      "getprofile()",
      "getdefaultencoding()",
      "intern(string)",
      "is_finalizing()",
    ],
    values: [
      "argv",
      "path",
      "version",
      "version_info",
      "platform",
      "executable",
      "modules",
      "stdout",
      "stderr",
      "stdin",
      "maxsize",
      "byteorder",
      "prefix",
      "exec_prefix",
      "flags",
      "dont_write_bytecode",
    ],
  },
  tempfile: {
    functions: [
      "mkstemp(suffix, prefix, dir, text)",
      "mkdtemp(suffix, prefix, dir)",
      "gettempdir()",
      "gettempdirb()",
      "gettempprefix()",
      "gettempprefixb()",
    ],
    classes: ["NamedTemporaryFile", "TemporaryFile", "TemporaryDirectory", "SpooledTemporaryFile"],
    values: ["tempdir", "TMP_MAX"],
  },
  textwrap: {
    functions: [
      "wrap(text, width, initial_indent, subsequent_indent, expand_tabs, replace_whitespace, fix_sentence_endings, break_long_words, drop_whitespace, break_on_hyphens, max_lines, placeholder)",
      "fill(text, width, initial_indent, subsequent_indent, expand_tabs, replace_whitespace, fix_sentence_endings, break_long_words, drop_whitespace, break_on_hyphens, max_lines, placeholder)",
      "shorten(text, width, placeholder)",
      "dedent(text)",
      "indent(text, prefix, predicate)",
    ],
    classes: ["TextWrapper"],
  },
  threading: {
    functions: [
      "current_thread()",
      "main_thread()",
      "active_count()",
      "enumerate()",
      "get_ident()",
      "get_native_id()",
      "stack_size(size)",
      "settrace(func)",
      "setprofile(func)",
    ],
    classes: [
      "Thread",
      "Lock",
      "RLock",
      "Event",
      "Condition",
      "Semaphore",
      "BoundedSemaphore",
      "Timer",
      "Barrier",
      "local",
    ],
    values: ["TIMEOUT_MAX"],
  },
  time: {
    functions: [
      "sleep(secs)",
      "time()",
      "perf_counter()",
      "monotonic()",
      "process_time()",
      "time_ns()",
      "perf_counter_ns()",
      "monotonic_ns()",
      "process_time_ns()",
      "thread_time()",
      "thread_time_ns()",
      "localtime(secs)",
      "gmtime(secs)",
      "strftime(format, t)",
      "strptime(string, format)",
      "asctime(t)",
      "ctime(secs)",
      "mktime(t)",
    ],
    classes: ["struct_time"],
    values: ["timezone", "altzone", "daylight", "tzname"],
  },
  tkinter: {
    functions: [
      "mainloop()",
      "Tcl(screenName, baseName, className, useTk)",
      "getint(s)",
      "getdouble(s)",
      "getboolean(s)",
      "NoDefaultRoot()",
    ],
    classes: [
      "Tk",
      "Toplevel",
      "Frame",
      "Label",
      "Button",
      "Entry",
      "Text",
      "Canvas",
      "Listbox",
      "Menu",
      "Checkbutton",
      "Radiobutton",
      "Scale",
      "Scrollbar",
      "Spinbox",
      "PhotoImage",
      "Variable",
      "StringVar",
      "IntVar",
      "DoubleVar",
      "BooleanVar",
      "Event",
      "Widget",
      "Misc",
      "TclError",
    ],
    values: [
      "LEFT",
      "RIGHT",
      "TOP",
      "BOTTOM",
      "END",
      "N",
      "S",
      "E",
      "W",
      "CENTER",
      "X",
      "Y",
      "BOTH",
      "NORMAL",
      "DISABLED",
      "ACTIVE",
      "SUNKEN",
      "RAISED",
      "GROOVE",
      "RIDGE",
      "FLAT",
      "HORIZONTAL",
      "VERTICAL",
      "TRUE",
      "FALSE",
    ],
  },
  traceback: {
    functions: [
      "print_exc(limit, file, chain)",
      "format_exc(limit, chain)",
      "print_exception(exc, limit, file, chain)",
      "format_exception(exc, limit, chain)",
      "print_tb(tb, limit, file)",
      "format_tb(tb, limit)",
      "extract_tb(tb, limit)",
      "extract_stack(f, limit)",
      "print_stack(f, limit, file)",
      "format_stack(f, limit)",
      "format_exception_only(exc, value)",
    ],
    classes: ["TracebackException", "StackSummary", "FrameSummary"],
  },
  turtle: {
    functions: [
      "forward(distance)",
      "backward(distance)",
      "right(angle)",
      "left(angle)",
      "goto(x, y)",
      "pendown()",
      "penup()",
      "pensize(width)",
      "pencolor(*args)",
      "fillcolor(*args)",
      "color(*args)",
      "begin_fill()",
      "end_fill()",
      "circle(radius, extent, steps)",
      "dot(size, color)",
      "speed(speed)",
      "setheading(to_angle)",
      "home()",
      "write(arg, move, align, font)",
      "clear()",
      "reset()",
      "stamp()",
      "undo()",
      "shape(name)",
      "shapesize(stretch_wid, stretch_len, outline)",
      "bgcolor(*args)",
      "screensize(canvwidth, canvheight, bg)",
      "setup(width, height, startx, starty)",
      "title(titlestring)",
      "done()",
      "exitonclick()",
      "bye()",
      "mainloop()",
      "tracer(n, delay)",
      "update()",
      "hideturtle()",
      "showturtle()",
      "isvisible()",
      "position()",
      "pos()",
      "xcor()",
      "ycor()",
      "heading()",
      "distance(x, y)",
      "towards(x, y)",
      "clone()",
      "pen(pen, **pendict)",
      "width(width)",
      "isdown()",
      "filling()",
      "fd(distance)",
      "bk(distance)",
      "back(distance)",
      "rt(angle)",
      "lt(angle)",
      "seth(to_angle)",
      "setpos(x, y)",
      "setposition(x, y)",
      "setx(x)",
      "sety(y)",
      "pd()",
      "down()",
      "pu()",
      "up()",
      "turtlesize(stretch_wid, stretch_len, outline)",
      "resizemode(rmode)",
      "tilt(angle)",
      "tiltangle(angle)",
      "delay(delay)",
      "mode(mode)",
      "colormode(cmode)",
      "setundobuffer(size)",
      "begin_poly()",
      "end_poly()",
      "get_poly()",
      "getscreen()",
      "getturtle()",
      "clearstamp(stampid)",
      "clearstamps(n)",
      "undobufferentries()",
      "degrees(fullcircle)",
      "radians()",
      "onkey(fun, key)",
      "onkeypress(fun, key)",
      "onkeyrelease(fun, key)",
      "onclick(fun, btn, add)",
      "onscreenclick(fun, btn, add)",
      "ontimer(fun, t)",
      "listen(xdummy, ydummy)",
      "textinput(title, prompt)",
      "numinput(title, prompt, default, minval, maxval)",
      "getcanvas()",
      "register_shape(name, shape)",
      "addshape(name, shape)",
      "bgpic(picname)",
      "window_width()",
      "window_height()",
    ],
    classes: ["Turtle", "Screen", "Vec2D", "RawTurtle", "RawPen", "Shape", "ScrolledCanvas", "Pen"],
  },
  types: {
    functions: [
      "new_class(name, bases, kwds, exec_body)",
      "prepare_class(name, bases, kwds)",
      "resolve_bases(bases)",
    ],
    classes: [
      "SimpleNamespace",
      "MappingProxyType",
      "ModuleType",
      "FunctionType",
      "LambdaType",
      "MethodType",
      "GeneratorType",
      "CoroutineType",
      "AsyncGeneratorType",
      "TracebackType",
      "FrameType",
      "CodeType",
      "BuiltinFunctionType",
      "BuiltinMethodType",
      "MethodWrapperType",
      "WrapperDescriptorType",
      "MethodDescriptorType",
      "ClassMethodDescriptorType",
      "CellType",
      "GenericAlias",
      "UnionType",
      "NoneType",
      "NotImplementedType",
      "EllipsisType",
      "DynamicClassAttribute",
    ],
  },
  typing: {
    functions: [
      "cast(typ, val)",
      "get_type_hints(obj, globalns, localns, include_extras)",
      "get_args(tp)",
      "get_origin(tp)",
      "NewType(name, tp)",
      "overload(func)",
      "runtime_checkable(cls)",
      "final(f)",
      "no_type_check(arg)",
      "assert_type(val, typ)",
      "reveal_type(obj)",
      "dataclass_transform(**kwargs)",
    ],
    classes: [
      "Optional",
      "Union",
      "Any",
      "List",
      "Dict",
      "Tuple",
      "Set",
      "FrozenSet",
      "Callable",
      "Iterable",
      "Iterator",
      "Sequence",
      "Mapping",
      "MutableMapping",
      "MutableSequence",
      "Type",
      "TypeVar",
      "Generic",
      "Protocol",
      "NamedTuple",
      "TypedDict",
      "Literal",
      "Final",
      "ClassVar",
      "Annotated",
      "Self",
      "Never",
      "TypeAlias",
    ],
    values: ["TYPE_CHECKING"],
  },
  unicodedata: {
    functions: [
      "name(chr, default)",
      "lookup(name)",
      "category(chr)",
      "normalize(form, unistr)",
      "decimal(chr, default)",
      "digit(chr, default)",
      "numeric(chr, default)",
      "bidirectional(chr)",
      "combining(chr)",
      "east_asian_width(chr)",
      "decomposition(chr)",
      "mirror(chr)",
      "is_normalized(form, unistr)",
    ],
    values: ["unidata_version", "ucd_3_2_0"],
  },
  urllib: {
    functions: [
      "quote(string, safe, encoding, errors)",
      "unquote(string, encoding, errors)",
      "urlencode(query, doseq, safe, encoding, errors)",
      "urlparse(url, scheme, allow_fragments)",
      "urlsplit(url, scheme, allow_fragments)",
      "urljoin(base, url, allow_fragments)",
      "parse_qs(qs, keep_blank_values, strict_parsing, encoding, errors, max_num_fields, separator)",
      "parse_qsl(qs, keep_blank_values, strict_parsing, encoding, errors, max_num_fields, separator)",
      "quote_plus(string, safe, encoding, errors)",
      "unquote_plus(string, encoding, errors)",
      "urlunparse(components)",
      "urlunsplit(components)",
      "urlopen(url, data, timeout)",
      "urlretrieve(url, filename, reporthook, data)",
      "pathname2url(path)",
      "url2pathname(path)",
    ],
    classes: ["Request", "HTTPError", "URLError", "RobotFileParser"],
  },
  uuid: {
    functions: [
      "uuid4()",
      "uuid1(node, clock_seq)",
      "uuid3(namespace, name)",
      "uuid5(namespace, name)",
      "getnode()",
    ],
    classes: ["UUID", "SafeUUID"],
    values: ["NAMESPACE_DNS", "NAMESPACE_URL", "NAMESPACE_OID", "NAMESPACE_X500"],
  },
  warnings: {
    functions: [
      "warn(message, category, stacklevel, source, skip_file_prefixes)",
      "filterwarnings(action, message, category, module, lineno, append)",
      "simplefilter(action, category, lineno, append)",
      "catch_warnings(record, module, action, category, lineno, append)",
      "warn_explicit(message, category, filename, lineno, module, registry, module_globals)",
      "showwarning(message, category, filename, lineno, file, line)",
      "formatwarning(message, category, filename, lineno, line)",
      "resetwarnings()",
    ],
    classes: ["WarningMessage"],
    values: ["filters"],
  },
  zipfile: {
    functions: ["is_zipfile(filename)"],
    classes: ["ZipFile", "ZipInfo", "Path", "PyZipFile"],
    values: ["ZIP_STORED", "ZIP_DEFLATED", "ZIP_BZIP2", "ZIP_LZMA"],
  },
  zlib: {
    functions: [
      "compress(data, level, wbits)",
      "decompress(data, wbits, bufsize)",
      "compressobj(level, method, wbits, memLevel, strategy)",
      "decompressobj(wbits, zdict)",
      "crc32(data, value)",
      "adler32(data, value)",
    ],
    classes: ["error"],
    values: [
      "MAX_WBITS",
      "DEFLATED",
      "Z_DEFAULT_COMPRESSION",
      "Z_BEST_COMPRESSION",
      "Z_BEST_SPEED",
      "Z_NO_COMPRESSION",
      "Z_SYNC_FLUSH",
      "Z_FINISH",
      "Z_FULL_FLUSH",
    ],
  },
};
